# Generated by Django 3.2.7 on 2021-09-15 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBTest', '0001_initial'),
    ]

    operations = [

    ]
